Fix the XML declaration message to work with JUnit 3.8.1 or JUnit 4.
JUnit 3.8.1 (which is what's used on the device) uses a message
like "expected:<...1> but was:<...0>".

Junit 4 (which is included in vogar) uses a message like
"expected:<1.[1]> but was:<1.[0]>"

I'd also like to fix bug 2286423 so we don't inherit the JUnit 3.8.1
from the device's boot classpath.

Change-Id: Iaf89e10a1536bbb9aaadd71f653b70177f898734